// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace SharkSDKTool
{
	public class HttpModel:MonoBehaviour
	{
		private static volatile HttpModel _instance;
		private static object syncRoot = new object(); 
		private static  GameObject _container;

		private HttpModel():base()
		{
		}
		//get instance
		public static HttpModel Ins
		{
			get 
			{
				if(null == _instance)
				{
					_container = new GameObject();
					_container.name = "U3DSharkSDK";
					UnityEngine.Object.DontDestroyOnLoad(_container);
					lock(syncRoot)
					{
						if(null == _instance)
						{
							_instance = _container.AddComponent(typeof(HttpModel))as HttpModel;
						}
					}
				}
				return _instance; 
			}
		}

		//GET请求
		IEnumerator HttpGet(string url)
		{
			
			WWW www = new WWW (url);
			yield return www;
			
			if (www.error != null)
			{
				//GET请求失败
				DEBUG.Log("error is :"+ www.error);
				
			} else
			{
				//GET请求成功
				DEBUG.Log("request ok : " + www.text);
			}
		}
	}
}

